name: CrashEssentials
main: com.romanio0089.crashessentials.Main
version: 1.0.0
commands:
     realcrash:
        description: Crashes specified player Minecraft client (95% success rate).
        usage: /<command> <player>
     fakejavaerror:
        description: Kicks specified player from server with a fake Java exception that looks real.
        usage: /<command> <player> <seconds>
permissions:
     crashessentials.*:
        description: Permission for all CrashEssentials commands.
        children:
           crashessentials.realcrash: true
           crashessentials.fakejavaerror: true
     crashessentials.realcrash:
        description: Permission to use realcrash.
     crashessentials.fakejavaerror:
        description: Permission to use fakejavaerror.